version: 0.0
os: linux
files:
    - source: /
      destination: /app/NDE-Frontend
file_exists_behavior: OVERWRITE
hooks:
    AfterInstall:
        - location: deploy-scripts/prelim
          timeout: 300
          runas: root
        - location: deploy-scripts/start_npm_after_build
          timeout: 300
          runas: nde
        - location: deploy-scripts/start_services
          timeout: 300
          runas: root
    ApplicationStop:
        - location: deploy-scripts/stop_services
          timeout: 300
          runas: root
